-- Cole este SQL no Supabase em SQL Editor > New query > Run.
-- O servidor usa a SERVICE_ROLE_KEY no backend, então as tabelas ficam sem acesso público direto.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id text primary key,
  name text not null,
  image text not null,
  original_price numeric(12, 2) not null,
  real_price numeric(12, 2) not null,
  promo_percent numeric(5, 2) not null default 0,
  category_slug text not null default 'pc-gamer',
  category_name text not null default 'PC Gamer',
  updated_at timestamptz not null default now(),
  created_order integer
);

create table if not exists public.orders (
  id text primary key,
  user_id bigint not null references public.users(id) on delete restrict,
  transaction_id text,
  status text not null,
  total numeric(12, 2) not null,
  payment_variant text not null,
  customer_json jsonb not null,
  address_json jsonb not null,
  items_json jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  last_login_at timestamptz
);

-- Reparo para bancos onde admin_users ja existia com colunas faltando.
alter table public.admin_users add column if not exists name text;
alter table public.admin_users add column if not exists email text;
alter table public.admin_users add column if not exists password_hash text;
alter table public.admin_users add column if not exists active boolean not null default true;
alter table public.admin_users add column if not exists created_at timestamptz not null default now();
alter table public.admin_users add column if not exists last_login_at timestamptz;

update public.admin_users
set
  name = coalesce(nullif(name, ''), 'Administrador Enifler'),
  password_hash = coalesce(
    nullif(password_hash, ''),
    '93f88ee6dce0b7e1417bf6a93289e51a:bc7c20edd58fe84d5e1f9b85c8337fe2ea3c4ecc7527c94bea816f0edfccc3802ea3d890f910bc5851029523d424e3169351a21ac5f6a439aa2283bfcf5c919a'
  );

with admins_without_email as (
  select id, row_number() over (order by id) as position
  from public.admin_users
  where email is null or email = ''
)
update public.admin_users as admin
set email = case
  when admins_without_email.position = 1 then 'admin@enifler.local'
  else 'admin+' || admins_without_email.position || '@enifler.local'
end
from admins_without_email
where admin.id = admins_without_email.id;

insert into public.admin_users (name, email, password_hash, active)
select
  'Administrador Enifler',
  'admin@enifler.local',
  '93f88ee6dce0b7e1417bf6a93289e51a:bc7c20edd58fe84d5e1f9b85c8337fe2ea3c4ecc7527c94bea816f0edfccc3802ea3d890f910bc5851029523d424e3169351a21ac5f6a439aa2283bfcf5c919a',
  true
where not exists (select 1 from public.admin_users where email = 'admin@enifler.local');

alter table public.admin_users alter column name set not null;
alter table public.admin_users alter column email set not null;
alter table public.admin_users alter column password_hash set not null;
create unique index if not exists idx_admin_users_email_unique on public.admin_users(email);

create index if not exists idx_orders_user_id on public.orders(user_id);
create index if not exists idx_orders_transaction_id on public.orders(transaction_id);
create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_products_category_slug on public.products(category_slug);

alter table public.users enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.admin_users enable row level security;
